M = zeros(500, 500);
imshow(M);
set(gcf,'color','black');
line(randi(500,1,2), randi(500,1,2));
M = rgb2gray(imnoise(frame2im(getframe(gcf))));
close all;
imshow(M);
seuillage = M > 50;
% imshowpair(M,seuillage,'montage');
% The function hough() also returns the Standard Hough Transform, H, which is a
% parameter space matrix whose rows and columns correspond to rho and theta
% values respectively.
[H,echelle_theta,echelle_rho] = hough(seuillage);
% peaks = houghpeaks(H,numpeaks) locates peaks in the Hough transform
% matrix, H, generated by the hough function. numpeaks specifies the
% maximum number of peaks to identify. The function returns peaks a matrix
% that holds the row and column coordinates of the peaks.
% peaks = houghpeaks(H,numpeaks,Name,Value) controls aspects of the
% operation using name-value pair arguments.
resultatPeaks = houghpeaks(H,1);
rho = resultatPeaks(1);
theta = resultatPeaks(2);
imshow(seuillage);
if theta > 160 || theta < 20
    title('la ligne est horizontale');
else
    title('la ligne est invalide');
end
% lines = houghlines(BW,theta,rho,peaks) extracts line segments in the
% image BW associated with particular bins in a Hough transform. theta and
% rho are vectors returned by function hough. peaks is a matrix returned by
% the houghpeaks function that contains the row and column coordinates of
% the Hough transform bins to use in searching for line segments. The
% return value lines contains information about the extracted line
% segments.
resultatLignes = houghlines(M, echelle_theta, echelle_rho, resultatPeaks);
line([resultatLignes.point1(1),resultatLignes.point2(1)], [resultatLignes.point1(2),resultatLignes.point2(2)]);



